include theos/makefiles/common.mk

TOOL_NAME = inPulseDaemon
inPulseDaemon_FILES = main.mm InPulseDaemonDelegate.m GCDAsyncSocket.m
inPulseDaemon_FRAMEWORKS = CFNetwork UIKit

include $(THEOS_MAKE_PATH)/tool.mk
