include theos/makefiles/common.mk

APPLICATION_NAME = inPulse
inPulse_FILES = main.m inPulseApplication.mm RootViewController.mm

include $(THEOS_MAKE_PATH)/application.mk

#SUBPROJECTS = inPulseNotifier
#include $(FW_MAKEDIR)/aggregate.mk
